# Generated by Django 3.2.10 on 2021-12-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
        ('dataprocess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='collect_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocess.collecttarget'),
        ),
        migrations.AddField(
            model_name='collecttargetitem',
            name='collect_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocess.collecttarget'),
        ),
        migrations.AddField(
            model_name='authinfo',
            name='collect_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocess.collecttarget'),
        ),
    ]
