# Generated by Django 3.2.10 on 2021-12-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0004_auto_20211223_1633'),
        ('config', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
