version: "3.8"

services:
  yg-mariadb:
    image: mariadb:10.7.1
    container_name: yg-mariadb
    restart: always
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_HOST=yg-mariadb
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=ygenter
      - MYSQL_DATABASE=ygenter
      - MYSQL_USER=ygenter
      - MYSQL_PASSWORD=ygenter

  rabbitmq:
    image: rabbitmq:3.7.14-management-alpine
    container_name: yg-rabbitmq
    environment:
      - RABBITMQ_USER=ygenter
      - RABBITMQ_PASSWORD=ygenter
    ports:
      - "5672:5672"
      - "15672:15672"

  yg-data-analysis:
    image: data-analysis
    # image: python:3.9-alpine3.13 #python alpine
    container_name: yg-data-analysis
    restart: always
    depends_on:
      - yg-mariadb
    volumes:
      - ./data/log:/data/log
    environment:
      - MYSQL_DB=ygenter
      - MYSQL_USER=ygenter
      - MYSQL_PASSWORD=ygenter
    ports:
      - "0.0.0.0:8081:8000"
