# Generated by Django 3.2.10 on 2021-12-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialbladeItem',
            fields=[
                ('artist', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('uploads', models.IntegerField()),
                ('subscribers', models.IntegerField()),
                ('views', models.BigIntegerField()),
                ('user_created', models.TextField()),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('platform', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
            ],
        ),
    ]
