# Generated by Django 3.2.10 on 2022-01-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melon',
            name='fans',
            field=models.IntegerField(null=True),
        ),
    ]
