# Generated by Django 3.2.10 on 2022-01-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_alter_melon_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdtanglefacebook',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='crowdtangleinstagram',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='melon',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='socialbladetiktok',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='socialbladetwitter',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='socialbladetwitter2',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='socialbladeyoutube',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='spotify',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='vlive',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='weverse',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='weverse',
            name='weverses',
            field=models.IntegerField(null=True),
        ),
    ]
