# Generated by Django 3.2.10 on 2022-01-17 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_socialbladeyoutube_reserved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdtanglefacebook',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crowdtangleinstagram',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='melon',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socialbladetiktok',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socialbladetwitter',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socialbladetwitter2',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='spotify',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vlive',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weverse',
            name='reserved_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
