# Generated by Django 3.2.10 on 2022-01-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20220117_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdtanglefacebook',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='crowdtangleinstagram',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='melon',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='socialbladetiktok',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='socialbladetwitter',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='socialbladetwitter2',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='socialbladeyoutube',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='spotify',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='vlive',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='weverse',
            name='reserved_date',
        ),
    ]
