# Generated by Django 3.2.10 on 2022-01-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20220119_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crowdtanglefacebook',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='crowdtangleinstagram',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='melon',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='socialbladetiktok',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='socialbladetwitter',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='socialbladetwitter2',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='socialbladeyoutube',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='spotify',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='vlive',
            name='reserved_date',
        ),
        migrations.RemoveField(
            model_name='weverse',
            name='reserved_date',
        ),
    ]
