# Generated by Django 3.2.10 on 2022-01-19 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20220119_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdtanglefacebook',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='crowdtangleinstagram',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='melon',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socialbladetiktok',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socialbladetwitter',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socialbladetwitter2',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='socialbladeyoutube',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='spotify',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vlive',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='weverse',
            name='reserved_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
