# Generated by Django 3.2.10 on 2021-12-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecttarget',
            name='target_url',
            field=models.TextField(default=''),
        ),
    ]
