# Generated by Django 3.2.10 on 2022-01-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='url',
            field=models.TextField(),
        ),
    ]
