# Generated by Django 3.2.10 on 2021-12-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0002_alter_collecttarget_target_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artistprofile',
            table='artist_profile',
        ),
    ]
