# Generated by Django 3.2.10 on 2021-12-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprocess', '0003_alter_artistprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('url', models.TextField(unique=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'platform',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='collecttarget',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprocess.platform'),
        ),
    ]
