name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout to repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: cyw320712
          password: ${{ secrets.CR_PAT }}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/ygentertainment-project/data-analysis:latest
